language: php
php:
  - '7.0'
sudo: false
env:
  - JQUERY=1
  - JQUERY=2
  - JQUERY=3
  - DOCUMENTATION
node_js:
  - "stable"
install:
  - if [ -z "$JQUERY" ] ; then nvm install stable && npm install && npm install jquery@$JQUERY && npm test ; fi
  - if [ -z "$JQUERY" ] ; then echo "" ; fi