language: php
php:
  - '7.0'
sudo: false
env:
  - JQUERY=1
  - JQUERY=2
  - JQUERY=3
  - DOCUMENTATION=1
install:
  - if [ "$JQUERY" ] ; then nvm install stable ; fi
  - if [ "$JQUERY" ] ; then npm install ; fi
  - if [ "$JQUERY" ] ; then npm install jquery@$JQUERY ; fi
  - if [ "$JQUERY" ] ; then npm test ; fi

  - if [ "$DOCUMENTATION" ] ; then cd documentation && composer install couscous/couscous && couscous generate ; fi
script: echo "No PHP tests"
