language: node_js
sudo: false
env:
  - JQUERY=1
  - JQUERY=2
  - JQUERY=3
  - DOCUMENTATION
node_js:
  - "stable"
install:
  - if [ -z "$JQUERY" ]; then nvm install stable && npm install && npm install jquery@$JQUERY && npm test fi