language: php
php:
  - '7.0'
sudo: false
env:
  - JQUERY=1
  - JQUERY=2
  - JQUERY=3
  - DOCUMENTATION
node_js:
  - "stable"
install:
  - nvm install stable
  - npm install
  - if [ -z "$JQUERY" ] ; then npm install jquery@$JQUERY ; fi
  - if [ -z "$JQUERY" ] ; then npm test ; fi
  - if [ -z "$JQUERY" ] ; then echo "" ; fi
script: echo "No PHP tests"
